### PR TITLE
Improving Konbucase Icon

### PR DESCRIPTION
**Pull request by Fatih20**
PR from #45 
Please test this first and give additional feedbacks before I pixel fit them.

### CODE REVIEW

**Comment by ryonakano** [comment]
Screenshot from 2020-06-27 21-50-29

**Comment by Fatih20** [comment]
Can you test this one please? I was about to push this before you posted your comment XD. This one has more subtle gradient.

**Comment by Fatih20** [comment]
Here's the pixel fitting. Compile and test this first before merging, thanks!

**Comment by Fatih20** [comment]
Don't forget to credit me in the patch notes, haha.
Also, here's a video of the process if you're interested.
https://open.lbry.com/@Fatih109:4/Konbucase:4?r=3r6R1wGsDKz76CrjA43SEhst8E9TKcgZ

**Comment by ryonakano** [comment]
I've just released the latest version of Konbucase, and credited you in [the release note](https://github.com/ryonakano/konbucase/releases/tag/2.0.0). It should be available on AppCenter in a few weeks.

That's an interesting video! You'd made really sweet icons for third-party apps designed for elementary OS. :heart_eyes:

**Comment by Fatih20** [comment]
> I've just released the latest version of Konbucase, and credited you in [the release note](https://github.com/ryonakano/konbucase/releases/tag/2.0.0). It should be available on AppCenter in a few weeks.
> 
> That's an interesting video! You'd made really sweet icons for third-party apps designed for elementary OS. heart_eyes

Thank you!

**Pull request merged**
