### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by safak45x**
tr.po add pls

### CODE REVIEW

**Comment by ryonakano** [comment]
Hi, thank you again for your translation!

I've just edited the another LINGUAS file in `po/extra` and generated translation files for Turkish. Would you mind adding Turkish translations in the generated translation files while we're here (not only adding `tr` to LINGUAS)?

**Comment by safak45x** [comment]
okey 5min I'm here with translation

**Comment by safak45x** [comment]
Would I do it tomorrow? I have some work done

**Comment by safak45x** [comment]
[tr.po.zip](https://github.com/ryonakano/konbucase/files/5286239/tr.po.zip)
finish

**Comment by safak45x** [comment]
Can I make a request from you while I'm here

**Comment by ryonakano** [comment]
> Can I make a request from you while I'm here

Yes, of course!

**Comment by safak45x** [comment]
2020-09-26 09-32-36 ekran görüntüsü
Would you develop an application that I can follow these kinds of football matches ?

**Comment by safak45x** [comment]
EOS appcenter one of the biggest shortcomings

**Comment by ryonakano** [comment]
Ah, I thought you may ask me about some missing features or bugs in Konbucase lol

Yes, I'll take a look. Do you mean this application that has been available until elementary OS Loki? https://github.com/mirkobrombin/Football

**Comment by safak45x** [comment]
I am aware: D
I said when there was a developer ready
It is not suitable for the new version and it will be better with new features.

**Comment by safak45x** [comment]
If you want, I can prepare a concept design

**Comment by ryonakano** [comment]
> If you want, I can prepare a concept design

Yes, I'd like you to do so.

**Comment by safak45x** [comment]
Is there an email I can contact

**Comment by ryonakano** [comment]
OK, send your concept design to m7509434116@lost-corona.com. You can send me in this conversation by attaching the file though.

**Comment by safak45x** [comment]
When will the Turkish patch of the application be released

**Comment by ryonakano** [comment]
Thank you for your mockup, I received it. I'll begin development of it in a few days!

> When will the Turkish patch of the application be released

It's not decided, I'll release a new version of the app when patches are piled.

**Review by ryonakano — APPROVED** [review]

**Comment by ryonakano** [comment]
@safak45x I've been working on development of the app you requested here: https://github.com/ryonakano/handy-football

It's still skeleton and does not fetch any football scores at the moment actually, but I would appreciate your feature requests or issue reports!

**Comment by safak45x** [comment]
> @ safak45x Burada talep ettiğiniz uygulamanın geliştirilmesi üzerinde çalışıyorum: https://github.com/ryonakano/handy-football
> 
> Hala iskelet ve şu anda herhangi bir futbol skoru getirmiyor, ancak özellik istekleriniz veya sorun raporlarınız için minnettar olurum!

Of course
Be sure that I will tell all the shortcomings and the necessary features as much as I can.

**Comment by safak45x** [comment]
Hey I couldn't install the app, please help handy football

**Pull request merged**
